### ISSUE TITLE
Doesn'y work on RHEL 8.6

### ISSUE THREAD

**Issue by slimeril** [luckylittle/CopyQ-for-RHEL8#2]
No icon in tray
```
cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.6 (Ootpa)
uname -a
Linux svitnin.tlv.csb 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Mon Jul 18 11:14:02 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yaozzzhao** [comment]
> No icon in tray
> 
> ```
> cat /etc/redhat-release 
> Red Hat Enterprise Linux release 8.6 (Ootpa)
> uname -a
> Linux svitnin.tlv.csb 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Mon Jul 18 11:14:02 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
> ```

I also met this issue. It prompts as below after launching copyq

Warning: [default] QtWarning: QSystemTrayIcon::setVisible: No Icon set

**Comment by yaozzzhao** [comment]
Warning: [default] QtWarning: QSystemTrayIcon::setVisible: No Icon set

**Comment by luckylittle** [comment]
@slimeril @yaozzzhao This was related to https://github.com/hluk/CopyQ/issues/2009

I tested the latest `6.3.2` on `4.18.0-372.26.1.el8_6.x86_64` and it work
